# Generated by Django 5.1.5 on 2025-03-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
    ]
