# Generated by Django 5.1.5 on 2025-03-16 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_labels_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_labels',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.task'),
        ),
    ]
