# Generated by Django 5.2.1 on 2025-05-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_remove_label_tasks'),
        ('tasks', '0005_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.tasks_labels', through_fields=('task', 'label'), to='labels.label'),
        ),
    ]
